### ISSUE TITLE
Failed to start initial cloud-init job

### ISSUE THREAD

**Issue by hosnerm** [duckietown/duckietown-shell-commands#95] opened 2019-02-21 09:52 UTC
Hi everyone! 
i reflashed several SD cards with the init_sd_card command and it worked without error. When trying to ping the host i do not get any response and cannot see it being connected to the router via admin interface. Therefore i connected it to a screen and saw that it had the following booting error: 

![img_4551](https://user-images.githubusercontent.com/39829590/53158307-8f43f080-35c3-11e9-8a07-940e42abdf6c.JPG)

therefore went to check the `systemctl status cloud-init.service` and got this: 
![img_4553](https://user-images.githubusercontent.com/39829590/53158841-daaace80-35c4-11e9-9982-8d6f4b13fcea.JPG)

i tried it with several SD cards, Duckiebots and Computers and still get this result, can anyone maybe help me with this? 

additional info: 

for the initialization i ran: 
`dts init_sd_card --hostname hostnamexy --wifi wifiname:passwd --country CH --compress`

i used: 
`duckietown-shell 3.0.31`
`Duckietown Shell commands version 1.1.1`

deleting and reconfiguring the `~/.dt-shell` didn't help either

**Comment by AmaurX** [comment] 2019-02-21 12:31
I think the issue is with the robotarium network right now. I am not sure the errors you are seeing have any thing to do with it, I had them before once.

**Comment by hosnerm** [comment] 2019-02-21 14:13
Were you able to resolve it back then? If yes, how did you do it?

**Comment by AmaurX** [comment] 2019-02-21 14:16
No not yet, we are looking into it with hopefully the help from IT people.
In the meantime I suggest you create your own hotspot with a phone, and connect your duckiebot to it if you just need to use it without the rest.

**Comment by AmaurX** [comment] 2019-03-01 15:54
@hosnerm you should close this issue

**Comment by AmaurX** [comment] 2019-03-11 16:22
@hosnerm you should close this issue

**Closed** 2023-01-27 14:10 UTC
Labels: networking
