### ISSUE TITLE
dts init_sd_card not able to download image

### ISSUE THREAD

**Issue by jesima31** [duckietown/duckietown-shell-commands#357] opened 2023-01-27 07:14 UTC
I am trying to set up the SD card for Duckiebot in my Ubuntu 20.04 VM in my Windows 11 host. For the init_sd_card command, I am getting this error.  How to resolve it?

![image](https://user-images.githubusercontent.com/69472869/215029451-5441250d-84d6-4966-a78d-d441ccd6cc8d.png)

![Screenshot (68)](https://user-images.githubusercontent.com/69472869/215029103-baf0a44a-d5db-4c70-8a67-5000f1a7628e.png)

**Comment by jasonhu5** [comment] 2023-01-27 13:04
Have you logged in on `dts` with your Duckietown token?

Mentioned [here](https://docs.duckietown.org/daffy/opmanual_duckiebot/out/dt_account.html).

**Comment by jesima31** [comment] 2023-01-27 15:34
Yes. I have. 


![image (1)](https://user-images.githubusercontent.com/69472869/215124897-e8736afe-b4c3-4ade-9632-364957303d30.png)
![image](https://user-images.githubusercontent.com/69472869/215124622-f016333f-0243-45b4-815a-f2b0e125bfdd.png)

**Comment by jesima31** [comment] 2023-01-27 15:35
Actually, I was able to download earlier. Suddenly I am not able to.

**Comment by jasonhu5** [comment] 2023-01-27 15:46
That is interesting. I can reproduce the error, too. @afdaniele Could you please take a look. It probably have something to do with `dts/data/get` and this commit: https://github.com/duckietown/duckietown-shell-commands/commit/0d37b5ada00b62f30cab660bd4dba5723f3732c6

**Comment by jtorres52** [comment] 2023-01-30 10:41
I have the same problem. A few weeks ago I was able to init a sd card, now I get this error. The token is ok, I executed dts tok verify and it was successful.

**Comment by jasonhu5** [comment] 2023-01-30 17:09
@afdaniele As mentioned [here](https://github.com/duckietown/duckietown-shell-commands/pull/359#issuecomment-1408912867), another problem occurred because of [passing empty args](https://github.com/duckietown/duckietown-shell-commands/blob/95c0e7820e703b5f75ef04ba4db79178b1f04ee2/data/get/command.py#L61)

**Comment by afdaniele** [comment] 2023-01-30 20:14
This is now fixed!
Commits:
- https://github.com/duckietown/duckietown-shell-commands/commit/73572c95cd2000f449eb8a6366d3de665dcb947b
- https://github.com/duckietown/duckietown-shell-commands/commit/95c0e7820e703b5f75ef04ba4db79178b1f04ee2

**Closed as completed by afdaniele** 2023-01-30 20:14 UTC
