### ISSUE TITLE
dts desktop update error

### ISSUE THREAD

**Issue by AnPhan215** [duckietown/duckietown-shell-commands#288] opened 2021-06-15 02:49 UTC
I'm following Book Duckiebot operation manual and everything is fine in Unit C-3 except I cannot turn off the Duckiebot properly, it only turns off the Jetson but not the Rasberry Pi, the back, front light and the fan dont turn off either.
So I think it's probably because the battery hasn't been update yet, hence I go to Unit C-5, part 5.5 to update Duckiebattery. When I run dts desktop update I met this error:

```
dts :  Traceback (most recent call last):
    :    File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    :      httplib_response = self._make_request(
    :    File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    :      conn.request(method, url, **httplib_request_kw)
    :    File "/usr/lib/python3.8/http/client.py", line 1255, in request
    :      self._send_request(method, url, body, headers, encode_chunked)
    :    File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    :      self.endheaders(body, encode_chunked=encode_chunked)
    :    File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    :      self._send_output(message_body, encode_chunked=encode_chunked)
    :    File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    :      self.send(msg)
    :    File "/usr/lib/python3.8/http/client.py", line 950, in send
    :      self.connect()
    :    File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 43, in connect
    :      sock.connect(self.unix_socket)
    :  PermissionError: [Errno 13] Permission denied
    :  
    :  During handling of the above exception, another exception occurred:
    :  
    :  Traceback (most recent call last):
    :    File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    :      resp = conn.urlopen(
    :    File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    :      retries = retries.increment(
    :    File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    :      raise six.reraise(type(error), error, _stacktrace)
    :    File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    :      raise value.with_traceback(tb)
    :    File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    :      httplib_response = self._make_request(
    :    File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    :      conn.request(method, url, **httplib_request_kw)
    :    File "/usr/lib/python3.8/http/client.py", line 1255, in request
    :      self._send_request(method, url, body, headers, encode_chunked)
    :    File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    :      self.endheaders(body, encode_chunked=encode_chunked)
    :    File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    :      self._send_output(message_body, encode_chunked=encode_chunked)
    :    File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    :      self.send(msg)
    :    File "/usr/lib/python3.8/http/client.py", line 950, in send
    :      self.connect()
    :    File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 43, in connect
    :      sock.connect(self.unix_socket)
    :  urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))
    :  
    :  During handling of the above exception, another exception occurred:
    :  
    :  Traceback (most recent call last):
    :    File "/home/anphan/.local/lib/python3.8/site-packages/dt_shell/main.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/anphan/.local/lib/python3.8/site-packages/dt_shell/main.py", line 195, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/anphan/.local/lib/python3.8/site-packages/dt_shell/cli.py", line 278, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/anphan/.local/lib/python3.8/site-packages/dt_shell/dt_command_abs.py", line 41, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, " ".join(parts[1:]))
    :    File "/home/anphan/.local/lib/python3.8/site-packages/dt_shell/dt_command_abs.py", line 54, in do_command
    :      cls.command(shell, args)
    :    File "/home/anphan/.dt-shell/commands-multi/daffy/desktop/update/command.py", line 26, in command
    :      arch = get_endpoint_architecture(DEFAULT_MACHINE)
    :    File "/home/anphan/.dt-shell/commands-multi/daffy/utils/docker_utils.py", line 61, in get_endpoint_architecture
    :      epoint_arch = client.info()["Architecture"]
    :    File "/usr/lib/python3/dist-packages/docker/client.py", line 179, in info
    :      return self.api.info(*args, **kwargs)
    :    File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 95, in info
    :      return self._result(self._get(self._url("/info")), True)
    :    File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    :      return f(self, *args, **kwargs)
    :    File "/usr/lib/python3/dist-packages/docker/api/client.py", line 230, in _get
    :      return self.get(url, **self._set_request_timeout(kwargs))
    :    File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    :      return self.request('GET', url, **kwargs)
    :    File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    :      resp = self.send(prep, **send_kwargs)
    :    File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    :      r = adapter.send(request, **kwargs)
    :    File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    :      raise ConnectionError(err, request=request)
    :  requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

dts :  To report a bug, please also include the contents of /home/anphan/shell-debug-info.txt
```

Does anyone have any suggestion?

**Comment by jasonhu5** [comment] 2023-01-27 15:13
Duplicate of #290

**Closed as completed by jasonhu5** 2023-01-27 15:13 UTC
