### ISSUE TITLE
Error with Docker during init_sd_card command

### ISSUE THREAD

**Issue by Pippo94** [duckietown/duckietown-shell-commands#89] opened 2019-01-17 12:59 UTC
executing the dts init_sd_card_command gives me an error message concerning Docker:

dts :  I cannot communicate with Docker:
    :  400 Client Error: Bad Request ("client is newer than server (client API version: 1.35, server API version: 1.22)")

**Comment by breandan** [comment] 2019-01-22 15:37
This is caused by an old Docker version. What is the output of running `docker version --format '{{.Server}}' && docker version --format '{{.Client.DefaultAPIVersion}}'`? How did you install Docker on your local machine? You should be able to fix it by updating to a more recent Docker release.

**Comment by Pippo94** [comment] 2019-01-22 15:56
Thank you very much. 
Installing docker the way described in the Duckie manual wasn’t working, so I used ’sudo apt-get docker.io’. This version was way too old and I had to install docker-ce, which was also not working…
Finally it worked using ‚sudo apt-get install docker-ce=17.12.0~ce-0~ubuntu‘.

**Comment by breandan** [comment] 2019-01-29 15:17
Great, glad to hear it worked.

**Comment by liampaull** [comment] 2019-02-07 22:01
let's make a practice of only closing issues when the docs are updated

**Comment by jasonhu5** [comment] 2023-01-27 14:08
Docs link to docker official installation pages. `docker` version has seldom been identified as a cause in recent issues. Assuming not a problem anymore

**Closed by jasonhu5** 2023-01-27 14:08 UTC
