### ISSUE TITLE
dts challenges info throws exception

### ISSUE THREAD

**Issue by lennartalff** [duckietown/duckietown-shell-commands#99] opened 2019-04-03 13:48 UTC
```
dt> challenges info

dts :  Traceback (most recent call last):
    :    File "/home/lennartalff/.local/lib/python3.6/site-packages/dt_shell/remote.py", line 85, in make_server_request
    :      res = urllib.request.urlopen(req, timeout=timeout)
    :    File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    :      return opener.open(url, data, timeout)
    :    File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    :      response = meth(req, response)
    :    File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    :      'http', request, response, code, msg, hdrs)
    :    File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    :      return self._call_chain(*args)
    :    File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    :      result = func(*args)
    :    File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    :      raise HTTPError(req.full_url, code, msg, hdrs, fp)
    :  urllib.error.HTTPError: HTTP Error 500: Internal Server Error
    :  
    :  During handling of the above exception, another exception occurred:
    :  
    :  Traceback (most recent call last):
    :    File "/home/lennartalff/.local/lib/python3.6/site-packages/dt_shell/__init__.py", line 45, in cli_main
    :      cli_main_()
    :    File "/home/lennartalff/.local/lib/python3.6/site-packages/dt_shell/__init__.py", line 118, in cli_main_
    :      shell.cmdloop()
    :    File "/usr/lib/python3.6/cmd.py", line 138, in cmdloop
    :      stop = self.onecmd(line)
    :    File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/lennartalff/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 409, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/lennartalff/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 42, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, ' '.join(parts[1:]))
    :    File "/home/lennartalff/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 53, in do_command
    :      cls.command(shell, args)
    :    File "/home/lennartalff/.dt-shell/commands/challenges/info/command.py", line 15, in command
    :      info = get_dtserver_user_info(token)
    :    File "/home/lennartalff/.local/lib/python3.6/site-packages/dt_shell/remote.py", line 147, in get_dtserver_user_info
    :      return make_server_request(token, endpoint, data=data, method=method)
    :    File "/home/lennartalff/.local/lib/python3.6/site-packages/dt_shell/remote.py", line 92, in make_server_request
    :      raise ConnectionError(msg)
    :  dt_shell.remote.ConnectionError: Operation failed for https://challenges.duckietown.org/v4/info
    :  
    :  <html>
    :    <head>
    :      <title>Internal Server Error</title>
    :    </head>
    :    <body>
    :      <h1><p>Internal Server Error</p></h1>
    :      
    :    </body>
    :  </html>

dts :  Please report that you are using:
    :  
    :  duckietown-shell: 4.0.6
    :  duckietown-shell-commands: 4.0.1
    :  python: "3.6.7 (default, Oct 22 2018, 11:32:17) \n[GCC 8.2.0]"
```

**Comment by AndreaCensi** [comment] 2019-04-03 14:08
@lennartalff thanks for the report - we are upgrading the infrastructure. Please hold on as we solve this.

**Comment by AndreaCensi** [comment] 2019-04-11 15:15
Does it work now?

**Comment by RamiNaim** [comment] 2019-04-11 15:26
Good Day!
I had the same problem, but I have reinstalled DTS just 5 minutes ago and there was no error this time.

**Comment by liampaull** [comment] 2019-04-11 15:49
@AndreaCensi this problem persists for me when I run `dts challenges evaluate` in the `predictor_last` directory. I have just updated the shell. Running on OSX. Output:
```
ERROR:runner-local:Traceback (most recent call last):
  File "/project/src/duckietown-challenges/src/duckietown_challenges/rest.py", line 81, in make_server_request
    res = urllib.request.urlopen(req, timeout=timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 34, in runner_local_main
    runner_local_main_()
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 91, in runner_local_main_
    cd = get_challenge_description(token, one)
  File "/project/src/duckietown-challenges/src/duckietown_challenges/rest_methods.py", line 147, in get_challenge_description
    res = make_server_request(token, endpoint, data=data, method=method)
  File "/project/src/duckietown-challenges/src/duckietown_challenges/rest.py", line 88, in make_server_request
    raise ConnectionError(msg)
duckietown_challenges.rest.ConnectionError: Operation failed for https://challenges.duckietown.org/v4/api/challenges/aido2_simple_prediction_r1/description

<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>
```

**Comment by liampaull** [comment] 2019-04-11 15:50
if it's not the same problem I will file a new issue

**Comment by AndreaCensi** [comment] 2019-04-11 15:58
@liampaull is this for `dts challenges info` or for `evaluate`?

**Comment by liampaull** [comment] 2019-04-11 15:59
@AndreaCensi evaluate

reproduced on Ubuntu 18

**Comment by AndreaCensi** [comment] 2019-04-11 16:01
@liampaull reproduced

**Comment by AndreaCensi** [comment] 2019-04-11 16:07
@liampaull maybe fixed. Try again?

**Comment by liampaull** [comment] 2019-04-11 16:18
@AndreaCensi looks fixed. 
The last output that I get is:
```
INFO:runner-local:Find your output here: output
INFO:dts:Cannot get container local-evaluator: 404 Client Error: Not Found ("No such container: local-evaluator")
DEBUG:dts:monitoring graceful exit
```

**Comment by liampaull** [comment] 2019-04-11 16:18
but my `output` directory looks like it has everything it should (I think)

**Comment by AndreaCensi** [comment] 2019-04-11 16:24
@liampaull can ignore - that's an unfortunate race condition with container being created/finished.

**Comment by liampaull** [comment] 2019-04-11 16:27
great. closing.

**Closed by liampaull** 2019-04-11 16:27 UTC
Labels: bug
