### ISSUE TITLE
dts version fails with 'Could not load commands.' caused by 'SyntaxError: invalid syntax'

### ISSUE THREAD

**Issue by botterweck** [duckietown/duckietown-shell-commands#98] opened 2019-03-31 23:50 UTC
Installed clean Ubuntu 18.10
Followed Laptop Setup as described here http://docs.duckietown.org/DT19/opmanual_duckiebot/out/laptop_setup.html

At the end of step 4 (Duckietown Shell) I get "ERROR:dts: !   Could not load commands." which seems to be caused by multiple "SyntaxError: invalid syntax".

```
WARNING:dts:I cannot find the command path /home/gb/.dt-shell/commands

dts :  Downloading commands in /home/gb/.dt-shell/commands ...
Duckietown Shell commands version 4.0.1
ERROR:dts:


            !   Could not load commands.

                Cannot load command class 'challenges.info.command.DTCommand' (package='challenges.', command='info'): Traceback (most recent call last):
  File "/home/gb/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 376, in _load_commands
    klass = _load_class(spec)
  File "/home/gb/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 479, in _load_class
    mod = __import__(components[0])
  File "/home/gb/.dt-shell/commands/challenges/__init__.py", line 2, in <module>
    from .define import *
  File "/home/gb/.dt-shell/commands/challenges/define/__init__.py", line 1, in <module>
    from .command import *
  File "/home/gb/.dt-shell/commands/challenges/define/command.py", line 10, in <module>
    from dt_shell.remote import make_server_request
  File "/home/gb/.local/lib/python2.7/site-packages/dt_shell/remote.py", line 87
    data_read: bytes = res.read()
             ^
SyntaxError: invalid syntax

(more errors ommitted)
```

Full output attached as file
[error-dts-version.txt](https://github.com/duckietown/duckietown-shell-commands/files/3027310/error-dts-version.txt)
. 

Not sure if that is important but please note the version difference 4.0.1 vs. 4.0.2 in
INFO:dts:duckietown-shell 4.0.2
Duckietown Shell commands version 4.0.1

Any suggestions?

**Comment by breandan** [comment] 2019-04-01 00:41
It's caused by a Python3 migration issue. You could try the experimental Python 3 release: `sudo apt-get install python3 && pip3 install --no-cache-dir --user -U duckietown-shell`.

**Comment by botterweck** [comment] 2019-04-01 07:29
That seems to have fixed the problem for now.

Had to install pip3 as well. So the following seems to have done the trick:
```
sudo apt install python3
sudo apt install python3-pip
pip3 install --no-cache-dir --user -U duckietown-shell
```

**Comment by hosnerm** [comment] 2019-04-01 07:37
Did the same thing and it worked fine, but when i now try to run a command as '`dts start_gui_tools hostname`' or '`dts duckiebot keyboard_control hostname`' i get a "permission denied" error. 

full error msg here: 
[error_msg_dts.txt](https://github.com/duckietown/duckietown-shell-commands/files/3028180/error_msg_dts.txt)

**Comment by AndreaCensi** [comment] 2019-04-01 08:02
@breandan @breandan from now, we only support Python 3.

**Comment by liampaull** [comment] 2019-04-01 11:16
then the docs need to be updated http://docs.duckietown.org/DT19/opmanual_duckiebot/out/laptop_setup.html

**Comment by botterweck** [comment] 2019-04-01 12:20
I have now continued with the setup and get stuck in the Docker setup
http://docs.duckietown.org/DT19/opmanual_duckiebot/out/docker_setup.html
(Step 7.1). It seems that the Portainer interface is not available.

/var/log/syslog contains the following


```
Apr 28 18:57:32 duckiebot1 cloud-init[288]: .IOError: [Errno 2] No such file or directory: '/var/local/DT18_00_basic.yaml'
Apr 28 18:57:32 duckiebot1 cloud-init[288]: .IOError: [Errno 2] No such file or directory: '/var/local/DT18_01_health_stats.yaml'
Apr 28 18:57:32 duckiebot1 cloud-init[288]: Cloud-init v. 0.7.9 running 'init' at Sat, 28 Apr 2018 18:57:11 +0000. Up 23.18 seconds.
(lines on network device info ommitted)
Apr 28 18:57:32 duckiebot1 cloud-init[288]: 2018-04-28 18:57:23,679 - util.py[WARNING]: Failed to run bootcmd module bootcmd
Apr 28 18:57:32 duckiebot1 cloud-init[288]: 2018-04-28 18:57:23,699 - util.py[WARNING]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_bootcmd.py'>) failed
```

Longer log attached: [duckietown-docker-syslog.txt](https://github.com/duckietown/duckietown-shell-commands/files/3029284/duckietown-docker-syslog.txt)

This might no longer be a Duckietown Shell issue, but it _might_ be related to the switch to Python 3. So others trying to update Duckietown Shell and switching to Python might run into the same problem.

Any suggestions? Where would be the right place to ask questions about that issue?

**Comment by tanij** [comment] 2019-04-15 14:05
@AndreaCensi please update on this when possible

**Comment by AndreaCensi** [comment] 2019-04-15 15:12
@liampaull any idea on this?

relevant lines:
```
Apr 28 18:57:32 duckiebot1 systemd[1]: Starting Initial cloud-init job (metadata service crawler)...
Apr 28 18:57:32 duckiebot1 cloud-init[288]: Error for wireless request "Set Power Management" (8B2C) :
Apr 28 18:57:32 duckiebot1 cloud-init[288]:     invalid argument "False".
Apr 28 18:57:32 duckiebot1 cloud-init[288]: .IOError: [Errno 2] No such file or directory: '/var/local/DT18_00_basic.yaml'
Apr 28 18:57:32 duckiebot1 cloud-init[288]: .IOError: [Errno 2] No such file or directory: '/var/local/DT18_01_health_stats.yaml'
```

**Comment by liampaull** [comment] 2019-04-15 15:25
not really but some things have changed since the issue was filed, does it still persist? Sometimes if you are impatient on first boot funny things like this come up...

**Comment by AndreaCensi** [comment] 2019-04-15 20:50
agree - impatience

**Comment by afdaniele** [comment] 2019-09-09 22:56
@liampaull @AndreaCensi can we close this?

**Closed** 2019-09-10 20:44 UTC
Labels: bug
